name = "webpage-checker"
main = "index.js"
compatibility_date = "2024-01-01"

# cron job（every 5 mins）
[triggers]
crons = ["*/5 * * * *"]

# env or secrets
[vars]
SLACK_WEBHOOK_URL = "https://hooks.slack.com/services/YOUR/WEBHOOK/URL" 
